### PR TITLE
Added Miro extension with Claude support

### PR DESCRIPTION
**Pull request by Kr-Adarsh**
#12 This pull request enhances the Miro Chrome extension by integrating support for Claude Sonnet alongside ChatGPT. Key updates include:

1. Content Script Enhancements: Modified to detect and handle responses from both Claude and ChatGPT, ensuring users receive timely notifications.
2. Background Script Updates: Implemented logic to manage notifications for Claude, allowing seamless user experience across both platforms.
3. User Interface Adjustments: Updated the popup UI to reflect the dual functionality, improving usability.

### CODE REVIEW

**Review by Shailendra1703 — APPROVED** [review]
@Kr-Adarsh You have done a fantastic work, it detects the claude response perfectly and notifies at when it finishes the response, but in case of GPT it notifies at the beginning of the conversations.

can you please look into it

**Comment by Kr-Adarsh** [comment]
@Shailendra1703 Thank you for your kind words and apologies for the late reply. Actually, I got caught up with some other tasks, I'll look into this and make the necessary adjustments, will update you when it's done 👍

**Comment by Shailendra1703** [comment]
> @Shailendra1703 Thank you for your kind words and apologies for the late reply. Actually, I got caught up with some other tasks, I'll look into this and make the necessary adjustments, will update you when it's done 👍

Sure @Kr-Adarsh, take your time btw GPT responses detections are working fine now, but we have some merge conflicts in this PR so we need to look on them.

**Comment by Kr-Adarsh** [comment]
@Shailendra1703 I've resolved the issues. Please look into it..

**Comment by Shailendra1703** [comment]
> @Shailendra1703 I've resolved the issues. Please look into it..

Hello @Kr-Adarsh, I'm getting this error while detecting the response of Claude sonnet and also it's not notifying, so can you please check this out?

Also the GPT response detection is working fine with Chrome webrequests so we don't need to use Mutations observers for that case.

image

**Comment by Kr-Adarsh** [comment]
> > @Shailendra1703 I've resolved the issues. Please look into it..
> 
> Hello @Kr-Adarsh, I'm getting this error while detecting the response of Claude sonnet and also it's not notifying, so can you please check this out?
> 
> Also the GPT response detection is working fine with Chrome webrequests so we don't need to use Mutations observers for that case.
> 
> image

Hii @Shailendra1703 Firstly, I'd like to apologise for not sharing consistent updates. I got engaged with some college work and other stuff, but I've been working on this issue since last evening, this error seems to not go; it's working sometimes and then suddenly stops working for Claude. I'm trying different routes to avoid these errors, and I'll get back to you soon with the good news. Thanks for your patience..

**Comment by Shailendra1703** [comment]
> > > @Shailendra1703 I've resolved the issues. Please look into it..
> > 
> > 
> > Hello @Kr-Adarsh, I'm getting this error while detecting the response of Claude sonnet and also it's not notifying, so can you please check this out?
> > Also the GPT response detection is working fine with Chrome webrequests so we don't need to use Mutations observers for that case.
> > image
> 
> Hii @Shailendra1703 Firstly, I'd like to apologise for not sharing consistent updates. I got engaged with some college work and other stuff, but I've been working on this issue since last evening, this error seems to not go; it's working sometimes and then suddenly stops working for Claude. I'm trying different routes to avoid these errors, and I'll get back to you soon with the good news. Thanks for your patience..

Hey @Kr-Adarsh ,  don't worry buddy I completely understand, take your time and you can ask your doubts anytime. open source is all about community feedbacks and that's how we learn and grow together. 

Btw I'm grateful to have you as a contributor on this project.

 You can check thd PR's by @mdtausifiqbal, he worked on the calude support via chrome webrequests, it was a very good approach.

**Comment by Kr-Adarsh** [comment]
@Shailendra1703 I made quite a lot of changes to the code, and it's working for both, but the error in the extension section keeps coming. I'm unable to resolve them.
Here take a look: 

https://github.com/user-attachments/assets/0e5e2f68-9ae1-405f-89ce-9478b89aefe3

Errors: 
Screenshot 2024-10-24 021203
Screenshot 2024-10-24 021156
Screenshot 2024-10-24 021145

@mdtausifiqbal could you please help on this..

**Comment by Kr-Adarsh** [comment]
@Shailendra1703, please check the changes; now it's not giving any errors and is working fine for both the AIs'.

**Comment by Shailendra1703** [comment]
> @Shailendra1703 I made quite a lot of changes to the code, and it's working for both, but the error in the extension section keeps coming. I'm unable to resolve them. Here take a look:
> 
>  Screen.Recording.2024-10-24.020719.mp4 
> Errors: Screenshot 2024-10-24 021203 Screenshot 2024-10-24 021156 Screenshot 2024-10-24 021145
> 
> @mdtausifiqbal could you please help on this..



Hello @Kr-Adarsh, I apologize for my delayed response; I got caught up with some office work. Regarding the error mentioned above, I'm not entirely sure of its cause. Based on my knowledge, I believe it may be due to the unavailability of `chrome.runtime`. I encountered a similar issue before, which resolved on its own ( #2  ) , so it might be related to the `content.js` file.

**Comment by Shailendra1703** [comment]
> @Shailendra1703, please check the changes; now it's not giving any errors and is working fine for both the AIs'.

Great, I approved your changes and long back ago, unfortunately, I can't merge this PR as the code we have right now is very much similar to our existing code, but I'm really glad to have you as a contributor on this project.

Thanks @Kr-Adarsh ❤️

**Comment by Kr-Adarsh** [comment]
> > @Shailendra1703, please check the changes; now it's not giving any errors and is working fine for both the AIs'.
> 
> Great, I approved your changes and long back ago, unfortunately, I can't merge this PR as the code we have right now is very much similar to our existing code, but I'm really glad to have you as a contributor on this project.
> 
> Thanks @Kr-Adarsh ❤️

The pleasure is all mine's. This project helped me learn so many new things that I might have skipped.  Thanks @Shailendra1703, if I'm able to I'd love to contribute on your upcoming projects.🙌🏻❤️

**Comment by Shailendra1703** [comment]
> > > @Shailendra1703, please check the changes; now it's not giving any errors and is working fine for both the AIs'.
> > 
> > 
> > Great, I approved your changes and long back ago, unfortunately, I can't merge this PR as the code we have right now is very much similar to our existing code, but I'm really glad to have you as a contributor on this project.
> > Thanks @Kr-Adarsh ❤️
> 
> The pleasure is all mine's. This project helped me learn so many new things that I might have skipped. Thanks @Shailendra1703, if I'm able to I'd love to contribute on your upcoming projects.🙌🏻❤️

Sure, would love to collaborate.

**Pull request closed without merging**
