### PR TITLE
Add favicon to the site

### PR DESCRIPTION
**Pull request by Sandigupta**
@Shailendra1703  Please merge this PR. as I added the website's icon.
Thank you
Screenshot 2024-10-15 002515

### CODE REVIEW

**Comment by Sandigupta** [comment]
@Shailendra1703 Please merge the PR.
Thanks.

**Comment by Shailendra1703** [comment]
Hello @Sandigupta , thanks for the PR but it's not a website, it's a chrome extensions while that favicon works well for the site but it didn't actually worked for chrome extension 
image

can you please check on that

**Comment by Sandigupta** [comment]
Okay, I am doing it.

**Comment by Sandigupta** [comment]
@Shailendra1703 
Can you merge this PR.

**Review by Shailendra1703 — APPROVED** [review]
@Sandigupta  can you please look on the above comment, I guess you haven't tackled that case yet.

**Comment by Sandigupta** [comment]
Okay, I am doing it.

**Pull request closed without merging**
