### PR TITLE
Fixes notification after streaming response #9

### PR DESCRIPTION
**Pull request by mdtausifiqbal**
I have fixed issue #9, now It will show notification on beginning and ending of response.

### CODE REVIEW

**Comment by mdtausifiqbal** [comment]
@Shailendra1703 please add hacktoberfest label to this PR.

**Comment by Shailendra1703** [comment]
> @Shailendra1703 please add hacktoberfest label to this PR.

Great work @mdtausifiqbal , I'll review it.

**Comment by Shailendra1703** [comment]
@mdtausifiqbal You have done a great job, while it shows the streaming and end of the response notifications on the GPT interface but when I tested on switching to other tabs in the browser it didn't sent me the notifications, so can you consider that test case as well?

**Comment by mdtausifiqbal** [comment]
Ok I will check.

**Review by Shailendra1703 — APPROVED** [review]

**Pull request closed without merging**
